# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87144c48e60aaf6571f63a9b7a1ad916296132f5fbe04ae5cb11b1ace5eb23e6c45bd89acd570eeab14f805db36cd8a4f9823f8c9428b8059cbfa26137ee77c9

test:
  secret_key_base: 4b53cef6b410ec4ec4f98d103608b2346bc77b294345c1466652b733cbfbac0affa6555c4ffa4306346d26c5b8b1753093c173746c1458344079a56d9eb86a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
